# Generated by Django 5.0.6 on 2024-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='Default Session Name', max_length=255),
        ),
    ]
