# Generated by Django 5.0.6 on 2024-08-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context',
        ),
        migrations.RemoveField(
            model_name='message',
            name='context',
        ),
    ]
