# Generated by Django 5.0.6 on 2024-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatsession_context_remove_message_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
